### ISSUE TITLE
Problema con el JS del carrusel

### ISSUE THREAD

**Issue by martincastro1575** [marcasmal/OtroRepositorioTest#1]
## En que puedo ayudar
El repositorio ha dejado de funcionar [ ]
Esta faltando algun archivo [ ]
Otro [x ]

Especifique:
Estan faltando archivos js para funcionamiento del carrusel

**Comment by marcasmal** [comment]
Debes crear un archivo llamado carr.js y pegar el codigo que esta dentro de la carpeta js

**Comment by marcasmal** [comment]
resuelto
